root: true
env:
  node: true
  jest: true
  browser: true
extends:
  - "plugin:prettier/recommended"
  - "plugin:react/recommended"
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: "module"
  ecmaFeatures:
    jsx: true
settings:
  react:
    pragma: "React"
    version: "detect"